[cr147][Android] Fix for upstream resources visibility
Othewise we get this error:
../../chrome/android/java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettings.java:9: error: cannot find symbol
import static org.chromium.ui.R.drawable.gshield_colorful;

Chromium changes:
https://chromium.googlesource.com/chromium/src/+/19b12eb71387041c442d1bf1dc9c98366f255ab7

commit 19b12eb71387041c442d1bf1dc9c98366f255ab7
Author: Liz Prucka <lizprucka@google.com>
Date:   Wed Feb 11 08:16:24 2026 -0800

    Upstreaming Clank OsAdditionalSecurityPermissionProviderImpl

    Upstreaming Advanced Protection provider class in Chrome components to
    allow for implementation across Chrome components and use in public apk.

    Separating browser messenger components in
    OsAdditionalSecurityPermissionProviderImpl.java to allow for inclusion
    of only core features in WebView.

    Updated AdvancedProtectionMediatorTest to use application context to
    fix resource loading errors in mock.

    Removed IDS_ADVANCED_PROTECTION_MESSAGE_DISABLE_TITLE as it is no longer
    used.

    Created placeholder translation templates for new safe_browsing [grd
    file](https://chromium.googlesource.com/website/+/HEAD/site/developers/design-documents/ui-localization/index.md#add-a-new-grd_p_file).

    Bug: 477677919
    Change-Id: I4944734152979ee99e2a577b0d36af12b968fc2e
    Bypass-Check-License: Moved OsAdditionalSecurityProvider files
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7486643
    Reviewed-by: Ravjit Uppal <ravjit@chromium.org>
    Reviewed-by: Calder Kitagawa <ckitagawa@chromium.org>
    Commit-Queue: Liz Prucka <lizprucka@google.com>
    Cr-Commit-Position: refs/heads/main@{#1583249}